### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by sifanzzz** [UBC-MDS/OLS_regressor#60]
Hi team. This issue is set up to list out all the tasks so that we don't miss anything before submission.
There are 4 main tasks this week (details [here](https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone4/milestone4.html))

- [x] **Setup GitHub actions workflow for continuous integration**
- [x] **Setup GitHub actions workflow for continuous deployment**
- [x] #76
- [x] **Address feedback to improve the project(listed below)**

For the **Address feedback to improve the project**,  here are what we can do:
(Notice: please use create the commit messages that address the feedback something like this:
**fix: Feedback addressed by ...**)

- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #66
- [x] #71
- [x] #72
- [x] #65
- [x] #73
- [x] #74
- [x] #75
- [x] #79
- [x] #80
- [x] #81
- [x] #83

Tick the checklist when it is finished.
Also check this [review page](https://github.com/UBC-MDS/software-review-2024/issues/21) for details.

**Comment by WaleedMahmood1** [comment]
The `pytest-cov` dependency was already there in the `pyproject.toml` file from before. So I didn't update/incorporate that peer review feedback. I created a new branch with the changes that I made. If someone could review it and merge with main, that would be awesome!

**Comment by sifanzzz** [comment]
maybe @charlesxch got this done before?

**Comment by WaleedMahmood1** [comment]
I think that since it is written at 5th place in the `tool.poetry.group.dev.dependencies` instead of 2nd place, like other packages, the reviewer missed it perhaps. @charlesxch could have gotten to resolving it beforehand too!

**Comment by charlesxch** [comment]
Yes, I think we are done with it and do not need to modify anything furthermore.
